---
# post sql commands already run with instance_DB.yml

- name: Run post drush commands - {{ instance.name }}
  ansible.builtin.command: "{{ instance.drush_path | default(drush_path) }} {{ instance.drush_profile | default('') }} {{ item }}"
  loop: '{{ instance.post_drush_commands | default([]) }}'
  when: drush_path | length > 0

- name: Run post commands - {{ instance.name }}
  become: "{{ item.become | default(false) }}"
  become_user: '{{ item.become_user | default(omit) }}'
  ansible.builtin.command: '{{ item.command }}'
  args:
    chdir: '{{ item.chdir | default(omit) }}'
  loop: '{{ instance.post_commands | default([]) }}'
