---
namespace: alphanodes
name: tasks
version: 1.0.1
readme: README.md
authors:
  - Alexander Meindl <a.meindl@alphanodes.com>
description: 'This collection provides application tasks for Debian and Ubuntu'
license:
  - Apache-2.0

tags:
  - application
  - backup
  - drupal
  - git
  - jekyll
  - lxc
  - matomo
  - nextcloud
  - redmine
  - sphinx
  - sync
  - watch

repository: 'https://github.com/alphanodes/ansible-collection-tasks/'
homepage: 'https://alphanodes.com'
issues: 'https://github.com/alphanodes/ansible-collection-tasks/issues'
build_ignore:
  - codecov.yml
  - .github
  - .gitignore
  - requirements.txt
  - .yamllint
