---

- name: Set repo_dir - {{ repo_spec.name }}
  ansible.builtin.set_fact:
    repo_dir: '{{ git_mirrors_root }}/{{ repo_spec.name }}'

- name: Mirror git repository - {{ repo_spec.name }}
  ansible.builtin.git:
    repo: '{{ repo_spec.repo }}'
    dest: '{{ repo_dir }}'
    version: '{{ repo_spec.version | default(omit) }}'
    bare: true
    force: true
  register: git_rc

- name: Push to remote server if repo changed - {{ repo_spec.name }}
  ansible.builtin.command: 'git push --mirror {{ repo_spec.push_to }}'
  args:
    chdir: '{{ repo_dir }}'
  when:
    - repo_spec.push_to is defined
    - git_rc.changed

- name: Call URL if repo changed
  ansible.builtin.uri:
    url: '{{ repo_spec.call_url }}'
  when:
    - repo_spec.call_url is defined
    - git_rc.changed
