---

- name: Set fact preferred_git_url (part 1)
  ansible.builtin.set_fact:
    preferred_git_url: "{{ 'write_url' if redmine_plugin_access == 'write' else 'url' }}"

- name: Set fact preferred_git_url (part 2)
  ansible.builtin.set_fact:
    preferred_git_url: "{{ 'https_url' if preferred_git_url == 'url' and redmine_plugin_access == 'https' else preferred_git_url }}"

- name: Include plugin tasks
  ansible.builtin.include_tasks: instance_plugin.yml
  tags:
    - redmine
    - plugin
  loop: "{{ instance.plugins | default([]) }}"
  loop_control:
    loop_var: plugin_name
