---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      changed_when: false

    - name: Install cron.
      ansible.builtin.apt:
        name: git
        state: present

  roles:
    - role: alphanodes.tasks.git_rollout
