---
- name: Set backup file name - mongodb databases
  ansible.builtin.set_fact:
    backup_file_name: "db-{{ date_stamp }}-{{ backup_file_period }}.mongo_archive"

# @see https://docs.mongodb.com/manual/reference/program/mongodump/
- name: Create mongodb dump
  ansible.builtin.shell: "mongodump {{ backup_mongodb_options }} > {{ backup_dir }}/{{ backup_file_name }}"

- name: Include encrypt file
  ansible.builtin.include_tasks: file_encrypt.yml
  vars:
    file_path: '{{ backup_dir }}/{{ backup_file_name }}'
    file_owner: root
  when: backup_file_encrypted

- name: Include checksum file
  ansible.builtin.include_tasks: file_checksum.yml
  vars:
    file_path: "{{ backup_dir }}/{{ backup_file_name + '.gpg' if backup_file_encrypted else backup_file_name }}"
    file_owner: root
  when: backup_create_hashfiles
