---
- name: Set backup file name - {{ db }}
  ansible.builtin.set_fact:
    backup_file_name: "db-{{ db }}-{{ date_stamp }}-{{ backup_file_period }}{{ backup_db_dump_format }}"

- name: Create MySQL dump - {{ db }}
  community.mysql.mysql_db:
    login_unix_socket: "{{ mysql_socket if mysql_root_plugin == 'auth_socket' else omit }}"
    name: '{{ db }}'
    target: "{{ backup_dir }}/{{ backup_file_name }}"
    dump_extra_args: '{{ backup_mysqldump_options | default(omit, true) }}'
    single_transaction: '{{ backup_mysql_single_transaction }}'
    quick: '{{ backup_mysql_quick }}'
    state: dump
  become: "{{ backup_mysql_become | default(omit) }}"
  become_user: '{{ backup_mysql_become_user | default(omit) }}'

- name: Include encrypt file
  ansible.builtin.include_tasks: file_encrypt.yml
  vars:
    file_path: '{{ backup_dir }}/{{ backup_file_name }}'
    file_owner: "{{ backup_mysql_become_user | default('root') }}"
  when: backup_file_encrypted

- name: Include checksum file
  ansible.builtin.include_tasks: file_checksum.yml
  vars:
    file_path: "{{ backup_dir }}/{{ backup_file_name + '.gpg' if backup_file_encrypted else backup_file_name }}"
    file_owner: "{{ backup_mysql_become_user | default('root') }}"
  when: backup_create_hashfiles
