---
- name: Set facts for backup file - {{ db.database }}
  ansible.builtin.set_fact:
    backup_file_name: "db-{{ db.database }}-{{ date_stamp }}-{{ backup_file_period }}.pg_dump"
    backup_file_owner: postgres

- name: Create postgresql dump - {{ db.database }}
  community.postgresql.postgresql_db:
    name: '{{ db.database }}'
    target: '{{ backup_dir }}/{{ backup_file_name }}'
    dump_extra_args: '{{ backup_postgresqldump_options }}'
    state: dump
  become_user: '{{ backup_file_owner }}'
  become: true

- name: Include encrypt file
  ansible.builtin.include_tasks: file_encrypt.yml
  vars:
    file_path: '{{ backup_dir }}/{{ backup_file_name }}'
    file_owner: '{{ backup_file_owner }}'
  when: backup_file_encrypted

- name: Include checksum file
  ansible.builtin.include_tasks: file_checksum.yml
  vars:
    file_path: "{{ backup_dir }}/{{ backup_file_name + '.gpg' if backup_file_encrypted else backup_file_name }}"
    file_owner: '{{ backup_file_owner }}'
  when: backup_create_hashfiles
