---

- name: Fail if dir is missing
  ansible.builtin.fail:
    msg: 'dir is missing for {{ instance.name }}'
  when: instance.dir is undefined or (instance.dir | length == 0)

- name: Run git clone/pull - {{ instance.name }}
  ansible.builtin.git:
    repo: '{{ instance.repo }}'
    dest: '{{ instance.dir }}'
    version: '{{ instance.repo_version | default(omit) }}'
    accept_hostkey: true
  register: repo_update

- name: Post command include for {{ instance.name }}
  ansible.builtin.include_tasks: instance_post_commands.yml
  tags:
    - post_commands
  when: >
    ((instance.post_commands is defined and instance.post_commands is iterable) or
    instance.post_uri is defined) and
    repo_update is defined and repo_update.changed
