---
- name: Converge
  hosts: all

  vars:
    backup_create_hashfiles: true
    backup_one_per_day_limit: false
    backup_sets:
      - name: etc
        src: /etc
      - name: root
        src: /root

  roles:
    - role: alphanodes.tasks.backup
