---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - barman
    - postgresql
  when: barman_task == 'setup'

- name: Include backup tasks
  ansible.builtin.include_tasks: backup.yml
  tags:
    - barman
    - backup
  when: barman_task == 'backup'
