---

- name: Include instance tasks
  ansible.builtin.include_tasks: instance.yml
  loop: "{{ jekyll_instances }}"
  loop_control:
    loop_var: instance
  when: >
    ((jekyll_rollout_instance | length == 0) or instance.name == jekyll_rollout_instance) and
    (instance.state is undefined or instance.state == 'active')
  tags: jekyll
