---
dependencies: []

galaxy_info:
  author: alexandermeindl
  description: system tasks - restart services or system reboot
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - services
    - systemd
    - reboot
    - restart
