---
# tasks for https://github.com/AlphaNodes/redmine_postgresql_search

- name: Update search index - {{ instance_name }}
  ansible.builtin.command: bash -lc "bundle exec rake redmine_postgresql_search:update_index"
  args:
    chdir: '{{ redmine_app_dir }}'
  register: update_index
  become: true
  become_user: '{{ redmine_user }}'
  environment:
    RAILS_ENV: '{{ redmine_rails_env }}'

- name: Output of update_index - {{ instance_name }}
  ansible.builtin.debug:
    var: update_index.stdout_lines
  when: update_index.stdout_lines | length > 0
