---
dependencies: []

galaxy_info:
  author: alexandermeindl
  description: Run Redmine rake tasks (receive mails, reminder, helpdesk mailer, recur-tasks)
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - redmine
