---
- name: Converge
  hosts: all

  vars:
    system_task_name: service_restart
    system_task_service_name: ssh

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      changed_when: false

  roles:
    - role: alphanodes.setup.ssh
    - role: alphanodes.tasks.system_task
