---
name: "alphanodes.tasks.matomo_task"
'on':
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'roles/matomo_task/**'
      - 'molecule/matomo_task/**'
      - '.github/workflows/matomo_task.yml'

defaults:
  run:
    working-directory: 'AlphaNodes.matomo_task'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    strategy:
      matrix:
        distro:
          - ubuntu2204
          - debian11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'AlphaNodes.matomo_task'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: |
          molecule --version
          molecule test -s matomo_task
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
