---
name: "alphanodes.tasks.project_sync"
'on':
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'roles/project_sync/**'
      - 'molecule/project_sync/**'
      - '.github/workflows/project_sync.yml'

defaults:
  run:
    working-directory: 'AlphaNodes.project_sync'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    strategy:
      matrix:
        distro:
          - ubuntu2204
          - debian11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: 'AlphaNodes.project_sync'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Molecule tests.
        run: |
          molecule --version
          molecule test -s project_sync
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
