---
name: "alphanodes.tasks.system_watch"
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'AlphaNodes.system_watch'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - debian11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'AlphaNodes.system_watch'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
